import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackButton from "@/components/back-button";
import MainMenu from "@/components/main-menu";
import Header from "@/components/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pause/break",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background h-dvh flex flex-col`}
      >
        <div className=" w-full flex flex-row border-b bg-[#FFF8F4] border-gray-800">
          <div className="p-4">
            <div className="flex flex-row">
              <p className="font-mono text-4xl font-black tracking-tighter">
                <Header/>
              </p>

              <BackButton />
            </div>

            <MainMenu />
          </div>
        </div>
        <div className="flex-1 min-h-0">{children}</div>
      </body>
    </html>
  );
}
